openapi: 3.0.2
info:
    title: Tarpe21_school_api
    version: 1.0.0
paths:
    '/users/{id}':
        summary: Handle users by its ID
        get:
            tags:
                - Users
            parameters:
                -
                    examples:
                        Get usersById:
                            value: '2'
                    name: id
                    description: |
                        Get all users by id
                    schema:
                        type: integer
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/users'
                            examples:
                                One User:
                                    value: |-
                                        [
                                            {
                                                "id": 2,
                                                "name": "Maler Kasum",
                                                "password": "3123"
                                                "group": "MAlpe21"
                                            },
                                            {
                                                "id": 35,
                                                "name": "Kasner Milen",
                                                "password": "12345678910",
                                                "group": "KASme31"
                                            }
                                        ]
                    description: |+
                        Success

                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                            examples:
                                error:
                                    value:
                                        ' error': User not found
                    description: |
                        Couldnt find a user
            summary: GET UsersById
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: array
                            items: {}
                        examples:
                            Put Example:
                                value: |4

                                        {
                                            "id": 3,
                                            "name": "Maleri Kasum",
                                            "password": "3123"
                                            "group": "MAlpe21"
                                        },
            tags:
                - Users
            parameters:
                -
                    examples:
                        PUTusersById:
                            value: '3'
                    name: id
                    description: Put Users By id
                    schema:
                        type: integer
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json: {}
                    description: |
                        Updated Users
            summary: PUT users
        delete:
            requestBody: {}
            tags:
                - Users
            parameters:
                -
                    examples:
                        Bob:
                            value: |
                                1
                    name: id
                    description: Delete Users by id
                    schema:
                        type: integer
                    in: path
                    required: true
            responses:
                '200':
                    description: Deleted User for the DB
                '404':
                    description: |
                        The User to be Deleted was not found
            summary: DELETE Users
        parameters:
            -
                examples:
                    john marston:
                        value: '4'
                name: id
                description: |
                    Get all users by id
                schema:
                    type: integer
                in: path
                required: true
    /Schools:
        get:
            tags:
                - School
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Schools'
                            examples:
                                Return all schools:
                                    value: "\t[ return {\"id\":g.id,\"name\":g.name,\"director\":g.director} ]"
                    description: |
                        GET Schools
            summary: GET Schools
        post:
            tags:
                - School
            summary: POST Schools
    '/Schools/{id}':
        get:
            tags:
                - School
        put:
            tags:
                - School
        delete:
            tags:
                - School
    /Lessons:
        get:
            tags:
                - Lessons
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Lessons'
                            examples:
                                Get lesson:
                                    value:
                                        -
                                            id: 32
                                            lessonsStart: some text
                                            lesson: some text
                                            length: some text
                                        -
                                            id: 28
                                            lessonsStart: some text
                                            lesson: some text
                                            length: some text
                    description: Succssesfuly Get
                '404':
                    description: Lesson not found
                '500':
                    description: Server err
            summary: Get lesson
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                $ref: '#/components/schemas/Lessons'
                        examples:
                            Add lessons:
                                value: |4-

                                        {
                                            "id": 59,
                                            "lessonsStart": "some text",
                                            "lesson": "some text",
                                            "length": "some text"
                                        }
            tags:
                - Lessons
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Lessons'
                            examples:
                                Post Lesson:
                                    value: |4

                                            {
                                                "id": 35,
                                                "lessonsStart": "some text",
                                                "lesson": "some text",
                                                "length": "some text"
                                            }
                    description: Successful Post
                '404':
                    description: Not found
            summary: Post lesson
    '/Lessons/{id}':
        get:
            tags:
                - Lessons
            parameters:
                -
                    examples:
                        Programming:
                            value: '7'
                    name: id
                    description: Get all lessons by id
                    schema:
                        type: integer
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Lessons'
                            examples:
                                ID:
                                    value:
                                        -
                                            id: 67
                                            lessonsStart: some text
                                            lesson: some text
                                        -
                                            id: 83
                                            lessonsStart: some text
                                            lesson: some text
                    description: Successful Get
                '404':
                    description: Could not find Lesson
        parameters:
            -
                examples:
                    Programming:
                        value: '7'
                name: id
                description: Get all lessons by id
                schema:
                    type: integer
                in: path
                required: true
    /Groups:
        get:
            tags:
                - Groups
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Groups'
                            examples:
                                Get all groups:
                                    value:
                                        -
                                            id: 29
                                            name: some text
                                            studentCount: 99
                                        -
                                            id: 83
                                            name: some text
                                            studentCount: 95
                    description: Successful Get
                '404':
                    description: Group no found
                '500':
                    description: Server err
            summary: GET groups
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                $ref: '#/components/schemas/Groups'
                        examples:
                            Post Group:
                                value: |4

                                        {
                                            "id": 19,
                                            "name": "some text",
                                            "studentCount": 47
                                        }
            tags:
                - Groups
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Groups'
                            examples:
                                Post Group:
                                    value:
                                        -
                                            id: 44
                                            name: some text
                                            studentCount: 14
                                        -
                                            id: 13
                                            name: some text
                                            studentCount: 6
                    description: Successful Post
            summary: POST group
    '/Groups/{id}':
        get:
            tags:
                - Groups
            parameters:
                -
                    examples:
                        Mvcpe21:
                            value: '7'
                    name: id
                    description: Get Groups by id
                    schema:
                        type: integer
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Groups'
                            examples:
                                ID:
                                    value:
                                        -
                                            id: 90
                                            name: some text
                                            studentCount: 60
                                        -
                                            id: 36
                                            name: some text
                                            studentCount: 32
                    description: Success
                '404':
                    description: Group not found
        parameters:
            -
                examples:
                    Mvcpe21:
                        value: '7'
                name: id
                description: Get Groups by id
                schema:
                    type: integer
                in: path
                required: true
    /users:
        get:
            tags:
                - Users
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/users'
                            examples:
                                Get users:
                                    value: |-
                                        [
                                            {
                                                "id": 64,
                                                "name": "Maler Kasum",
                                                "password": "3123"
                                                "group": "MAlpe21"
                                            },
                                            {
                                                "id": 35,
                                                "name": "Kasner Milen",
                                                "password": "12345678910",
                                                "group": "KASme31"
                                            }
                                        ]
                    description: GET all users
                '404':
                    description: Get not found
                '500':
                    description: Internal Server error
            summary: GET Users
        post:
            requestBody:
                description: ''
                content:
                    application/json:
                        schema:
                            type: array
                            items: {}
                        examples:
                            UsersPost:
                                value:
                                    id: 1
                                    name: Bob
                                    password: '1234'
                                    group: GALpe20
            tags:
                - Users
            responses:
                '200':
                    description: |
                        Users got Updated
            summary: POST Users
components:
    schemas:
        Error:
            title: Root Type for Error
            description: ''
            type: object
            properties:
                ' error':
                    type: string
            example:
                ' error': error message
        Groups:
            title: Root Type for Groups
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                studentCount:
                    format: int32
                    type: integer
            example:
                id: 1
                name: Tarpe21
                studentCount: 16
        Schools:
            title: Root Type for Schools
            description: '    '
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                Director:
                    type: string
            example:
                id: 1
                name: TTHK
                Director: Paul Alekand
        users:
            title: Root Type for Users
            description: '    '
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                password:
                    type: string
                group:
                    type: string
            example:
                id: 1
                name: Bob
                password: '1234'
                group: GALpe20
        Lessons:
            title: Root Type for Lesson
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                lessonsStart:
                    type: string
                lesson:
                    type: string
                length:
                    type: string
            example:
                id: 1
                lessonsStart: '9,30'
                lesson: Programming
                length: 45 min
