openapi: 3.0.2
info:
    title: School-Api
    version: 1.0.0
    description: |-
        ### This is a Swagger UI for our School-Api 

        ### Error handlingErrors are presented using the HTTP status codes 400-599.

        The response include a more detailed explanation about the error in the body.

        ```{  "error": "Cleartext explanation of the error that occurred"}```
        ### Generic API errors

        These error responses can be returned by any of the described endpoints.
        | HTTP status  |  Description |
        |---|---|
        | 400| Bad input parameters or invalid request. More information can be found in the response body.
        | 401| The consumer does not have access to the requested resource or the provided token is not valid.
        | 404| The requested resource can not be found or the user does not have access to the resource.
        | 5XX| A server error has occurred while processing the request.
paths:
    '/users/{id}':
        summary: Handle users by its ID
        get:
            tags:
                - Users
            parameters:
                -
                    examples:
                        Martin:
                            value: '3'
                    name: id
                    description: |
                        Get all users by id
                    schema:
                        type: integer
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                One User:
                                    value: '{id:3,name:"martin",password:''b_phi<ibh'',group:"TARpe21"},'
                    description: |+
                        Success

                '404':
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                            examples:
                                error:
                                    value:
                                        ' error': User not found
                    description: |
                        Couldnt find a user
        put:
            tags:
                - Users
            parameters:
                -
                    examples:
                        john marston:
                            value: '4'
                    name: id
                    description: |
                        Get all users by id
                    schema:
                        type: integer
                    in: path
                    required: true
            responses:
                '200':
                    description: |
                        Updated Users
            summary: PUT users
        delete:
            tags:
                - Users
            responses:
                '200':
                    description: Deleted Users
            summary: DELETE Users
        parameters:
            -
                examples:
                    john marston:
                        value: '4'
                name: id
                description: |
                    Get all users by id
                schema:
                    type: integer
                in: path
                required: true
    /Schools:
        get:
            tags:
                - School
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Schools'
                            examples:
                                Return all schools:
                                    value: "\t[ return {\"id\":g.id,\"name\":g.name,\"director\":g.director} ]"
                    description: |
                        GET Schools
            summary: GET Schools
        put:
            tags:
                - School
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                Put all schools:
                                    value: |+

            summary: PUT Schools
        post:
            tags:
                - School
            summary: POST Schools
        delete:
            tags:
                - School
            summary: DELETE Schools
    '/Schools/{id}':
        get:
            tags:
                - School
        put:
            tags:
                - School
        post:
            tags:
                - School
        delete:
            tags:
                - School
    /Lessons:
        get:
            tags:
                - Lessons
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Lessons'
                            examples:
                                Get lesson:
                                    value:
                                        -
                                            id: 49
                                            lessonsStart: some text
                                            lesson: some text
                                        -
                                            id: 20
                                            lessonsStart: some text
                                            lesson: some text
                    description: Succssesfuly Get
                '404':
                    description: Lesson not found
                '500':
                    description: Server err
            summary: Get lesson
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                $ref: '#/components/schemas/Lessons'
                        examples:
                            Add lessons:
                                value: |4

                                        {
                                            "id": 2,
                                            "lessonsStart": "some text",
                                            "lesson": "some text"
                                        }
            tags:
                - Lessons
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Lessons'
                            examples:
                                Post Lesson:
                                    value:
                                        -
                                            id: 91
                                            lessonsStart: some text
                                            lesson: some text
                                        -
                                            id: 89
                                            lessonsStart: some text
                                            lesson: some text
                    description: Successful Post
                '404':
                    description: Not found
            summary: Post lesson
    '/Lessons/{id}':
        get:
            tags:
                - Lessons
            parameters:
                -
                    examples:
                        Programming:
                            value: '7'
                    name: id
                    description: Get all lessons by id
                    schema:
                        type: integer
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                ID:
                                    value: |-
                                        let data = [
                                            {id: 1, LessonsStart: '9:30', Lesson:"Programming"},
                                            {id: 2, LessonsStart: '8.30', Lesson:"Biology"},
                                            {id: 3, LessonsStart: '12.45', Lesson:"P.E"},
                                            {id: 4, LessonsStart: '8.30', Lesson:"Math"}
                                        ]
                    description: Successful Get
                '404':
                    description: Could not find Lesson
        parameters:
            -
                examples:
                    Programming:
                        value: '7'
                name: id
                description: Get all lessons by id
                schema:
                    type: integer
                in: path
                required: true
    /Groups:
        get:
            tags:
                - Groups
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Groups'
                            examples:
                                Get all groups:
                                    value:
                                        -
                                            id: 29
                                            name: some text
                                            studentCount: 99
                                        -
                                            id: 83
                                            name: some text
                                            studentCount: 95
                    description: Successful Get
                '404':
                    description: Group no found
                '500':
                    description: Server err
            summary: GET groups
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            type: array
                            items:
                                $ref: '#/components/schemas/Groups'
                        examples:
                            Post Group:
                                value: |4

                                        {
                                            "id": 19,
                                            "name": "some text",
                                            "studentCount": 47
                                        }
            tags:
                - Groups
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Groups'
                            examples:
                                Post Group:
                                    value:
                                        -
                                            id: 44
                                            name: some text
                                            studentCount: 14
                                        -
                                            id: 13
                                            name: some text
                                            studentCount: 6
                    description: Successful Post
            summary: POST group
    '/Groups/{id}':
        get:
            tags:
                - Groups
            parameters:
                -
                    examples:
                        Mvcpe21:
                            value: '7'
                    name: id
                    description: Get Groups by id
                    schema:
                        type: integer
                    in: path
                    required: true
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: string
                            examples:
                                ID:
                                    value: |-
                                        let data = [
                                            { id: 1, name: "Tarpe21", Students: 16 },
                                            { id: 2, name: "Iot", Students:24  },
                                            { id: 3, name: "Mvcpe20", Students: 12 },
                                            { id: 4, name: "Tatge22", Students: 18 },
                                            { id: 5, name: "SoT", Students: 5 }
                                        ]
                    description: Success
                '404':
                    description: Group not found
        parameters:
            -
                examples:
                    Mvcpe21:
                        value: '7'
                name: id
                description: Get Groups by id
                schema:
                    type: integer
                in: path
                required: true
    /users:
        get:
            tags:
                - Users
            responses:
                '200':
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/users'
                            examples:
                                Get users:
                                    value: |-
                                        [
                                            {
                                                "id": 64,
                                                "name": "Maler Kasum",
                                                "password": "3123"
                                                "group": "MAlpe21"
                                            },
                                            {
                                                "id": 35,
                                                "name": "Kasner Milen",
                                                "password": "12345678910",
                                                "group": "KASme31"
                                            }
                                        ]
                    description: GET all users
                '404':
                    description: Get not found
                '500':
                    description: Internal Server error
            summary: GET Users
        post:
            requestBody: {}
            tags:
                - Users
            responses:
                '200':
                    description: |
                        Users got Updated
            summary: POST Users
components:
    schemas:
        Error:
            title: Root Type for Error
            description: ''
            type: object
            properties:
                ' error':
                    type: string
            example:
                ' error': error message
        Groups:
            title: Root Type for Groups
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                studentCount:
                    format: int32
                    type: integer
            example:
                id: 1
                name: Tarpe21
                studentCount: 16
        Schools:
            title: Root Type for Schools
            description: '    '
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                Director:
                    type: string
            example:
                id: 1
                name: TTHK
                Director: Paul Alekand
        Lessons:
            title: Root Type for Lessons
            description: ''
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                lessonsStart:
                    type: string
                lesson:
                    type: string
            example:
                id: 1
                lessonsStart: '9,30'
                lesson: Programming
        users:
            title: Root Type for Users
            description: '    '
            type: object
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                password:
                    type: string
                group:
                    type: string
            example:
                id: 1
                name: Bob
                password: 1234
                group: GALpe20

