summary: Handle users by its ID
get:
    tags:
        - users
    responses:
        '200':
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        One User:
                            value: '{id:3,name:"martin",password:''b_phi<ibh'',group:"TARpe21"},'
            description: |+
                Success

        '404':
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Error'
                    examples:
                        error:
                            value:
                                ' error': User not found
            description: |
                Couldnt find a user
parameters:
    -
        examples:
            john marston:
                value: '4'
        name: id
        description: |
            Get all users by id
        schema:
            type: integer
        in: path
        required: true
